### ISSUE TITLE
Can't build iOS sample code

### ISSUE THREAD

**Issue by stewardqq** [BelledonneCommunications/linphone-xamarin#13]
I'm trying debug sample code on iPhoneSimlator
when i build that i got three errors
any idea to fix?

liblinphone-xamarin-sdk-latest/LinphoneXamarin/LinphoneXamarin/LinphoneXamarin.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (LinphoneXamarin.iOS)

liblinphone-xamarin-sdk-latest/LinphoneXamarin/LinphoneXamarin/LinphoneXamarin.iOS/error MT5209: Error: framework not found mssilk (LinphoneXamarin.iOS) Native linking

liblinphone-xamarin-sdk-latest/LinphoneXamarin/LinphoneXamarin/LinphoneXamarin.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (LinphoneXamarin.iOS)

**Comment by stewardqq** [comment]
@hinnerkweiler 
I just downloaded  lastest version, and try compile it.  I got error "framework not found mediastreamer_base".
but I downloaded liblinphone-xamarin-sdk-3.12.0-2987-g66419a35f on 4, October , it compile success.

![image](https://user-images.githubusercontent.com/19276572/47762811-1f9ab480-dcf9-11e8-9028-3345dc12cbe4.PNG)

**Comment by hinnerkweiler** [comment]
Thanks for the hint, that worked for me too.
