### ISSUE TITLE
Incorrect enumeration of LogLevel in C# wrapper

### ISSUE THREAD

**Issue by anders9ustafsson** [BelledonneCommunications/linphone-xamarin#14]
In *linphone/logging.h*, the `LinphoneLogLevel` enumeration is defined like this:

    typedef enum _LinphoneLogLevel {
      LinphoneLogLevelDebug   = 1,
      LinphoneLogLevelTrace   = 1<<1,
      LinphoneLogLevelMessage = 1<<2,
      LinphoneLogLevelWarning = 1<<3,
      LinphoneLogLevelError   = 1<<4,
      LinphoneLogLevelFatal   = 1<<5
    } LinphoneLogLevel;

while currently, in the generated C# wrapper, the enumeration `LogLevel` is defined like this:

    public enum LogLevel
    {
      Debug = 1,
      Trace = 2,
      Message = 3,
      Warning = 4,
      Error = 5,
      Fatal = 6,
    }

For sufficient correspondence with the C baseline, the C# enumeration should instead be decorated with the `[Flags]` attribute and defined as follows:

    [Flags]
    public enum LogLevel
    {
      Debug = 1,
      Trace = 1<<1,
      Message = 1<<2,
      Warning = 1<<3,
      Error = 1<<4,
      Fatal = 1<<5
    }

**Comment by Viish** [comment]
Except for the [Flag] attribute, it has already been fixed in commit 832e4fc4ac3ea07071d53d601c8dd687122d13ab
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Wed Aug 8 09:06:59 2018 +0200
    Updated linphone

**Comment by Viish** [comment]
@anders9ustafsson thanks to your suggestion I added the [Flags] decorator in latest commit:
commit 2e8ba55060fbc690d8eaaa676a80c8fa4fc985e2
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Tue Sep 4 15:49:57 2018 +0200
    Updated submodules
