### ISSUE TITLE
Video is not being Displayed in Android

### ISSUE THREAD

**Issue by XamarinOrem** [BelledonneCommunications/linphone-xamarin#26]
I am setting the NativeVideoWindowId to Org.Linphone.Mediastream.Video.Display.GL2JNIView, But the video never shown up there, I tried with every possible solution. 

Can somebody help me to figure out whats wrong with it.

**Comment by Viish** [comment]
As you can see from our sample app, you have to create an AndroidVideoWindowImpl object from your GL2JNIView and give that object to NativeVideoWindowId.
```
AndroidVideoWindowImpl androidView = new AndroidVideoWindowImpl(displayCamera, captureCamera, null);
app.Core.NativeVideoWindowId = androidView.Handle;
```
Anyway I recommend you to switch to the use_linphone_sdk branch so you can simply create a TextureView and give it's handle to the Core, which is quite simple.

**Comment by XamarinOrem** [comment]
I am not handling this in the Main activity, Instead I am handling this on the content page itself. It does not work either. I am using this in this way because I have a background service and when the call arrives, I will display the user with a content page showing two buttons as 'Accept' and 'Reject'. When the user accepts the call, we will show him the video page and all the handler are done on that page itself. I am able to transmit the video by using this process but unfortunately, The video has not been received or not shown in the layout. My requirement is just to show the received video in the layout.

Can you please suggest me something to make this work.

**Comment by luisrr1590** [comment]
XamarinOrem did you find a solution for this????? I'm facing the exact same problem and my approach is identical to yours.
