### ISSUE TITLE
NativeVideoWindowId

### ISSUE THREAD

**Issue by Orma07** [BelledonneCommunications/linphone-xamarin#4]
Hi, I'm tring to use Linphone-xamarin to implement video call, but when I give id of my view to linphone core the view doesn't show me video. 

Is that wrong? 
` lc.NativeVideoWindowId = CallVideo.Id.ToString();` 

lc is my linphoneCore, CallVideo is my ContentView.

**Comment by anders9ustafsson** [comment]
@Orma07 Did you ever get a response to this question? I am struggling with finding the right handle to set myself right now.

**Comment by Orma07** [comment]
Belledonne have update the example

**Comment by anders9ustafsson** [comment]
Thanks, I have totally missed that.
