### ISSUE TITLE
Snapshot is missing

### ISSUE THREAD

**Issue by galisamas** [BelledonneCommunications/linphone-xamarin#6]
https://linphone.org/snapshots/xamarin/

can you please provide Xamarin snapshots? 

Moreover, compiling own wrapper fails with this:

make[6]: *** No rule to make target `coreapi/help/doc/doxygen/xml/index.xml', needed by `wrappers/csharp/LinphoneWrapper.cs'.  Stop.
make[5]: *** [wrappers/csharp/CMakeFiles/linphonecs.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/.../linphone-xamarin/android/android-arm64/Stamp/EP_linphone/EP_linphone-build] Error 2
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [android-arm64-build] Error 2

**Comment by jehandelalune** [comment]
https://linphone.org/releases/xamarin/

**Comment by galisamas** [comment]
great!
