### ISSUE TITLE
Invalid MonoPInvokeCallback in iOS

### ISSUE THREAD

**Issue by anders9ustafsson** [BelledonneCommunications/linphone-xamarin#8]
In the generated *LinphoneWrapper.cs*, the following delegate is declared within the `LinphoneObject` type:

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void OnLinphoneObjectDataDestroyed(IntPtr data);

The delegate is used in this decoration of the `LinphoneObject` finalizer:

    #if __IOS__
    [MonoPInvokeCallback(typeof(OnLinphoneObjectDataDestroyed))]
    #endif
    ~LinphoneObject() { ... }

Trying to build an iOS app containing the *LinphoneWrapper.cs* source code file yields the following error:

> AOT restriction: Method 'Linphone.LinphoneObject:Finalize ()' must be static since it is decorated with [MonoPInvokeCallback]. See http://ios.xamarin.com/Documentation/Limitations#Reverse_Callbacks

Which seems valid: the finalizer is not `static`, and also the delegate signature does not apply.

Is the `[MonoPInvokeCallback]` decoration of the `LinphoneObject` finalizer intended, or should the decoration be applied on another method? Is it safe to remove the decoration from the finalizer?

**Comment by XamarinOrem** [comment]
I am also facing this issue and not able to solve it, Please let me know how can I solve this?

**Comment by anders9ustafsson** [comment]
@XamarinOrem Please have a look at the commit referenced above, [here](https://github.com/nwisesweden/linphone/commit/19d21bde17f727255c01fc9a0d9d31246b383b45).

**Comment by MrAndrewAu** [comment]
Thank you @anders9ustafsson, you are a life saver 👍

**Comment by Viish** [comment]
Fixed in liblinphone commit 68f64b372704248ca84ff7ac51465e4da618c95f
